# Generated by Django 3.1.2 on 2021-09-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('emormob', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
